### PR TITLE
Update to use google maps and rainviewer radar images

### PR DESCRIPTION
**Pull request by kmcrawford**
image

### CODE REVIEW

**Comment by kmcrawford** [comment]
image

**Comment by JaredBanyard** [comment]
@kmcrawford Did you update the geo-ip api for the forecast page as well?

**Comment by JaredBanyard** [comment]
Testing in the car, looks good!

**Comment by kmcrawford** [comment]
> @kmcrawford Did you update the geo-ip api for the forecast page as well?

I didn't that api looks to be still working...

**Pull request merged**
